### ISSUE TITLE
Button event listener not doing the same as pressing enter?

### ISSUE THREAD

**Issue by developess** [fac-14/HMEN#38]
This is related to issue #33 

The event listener for pressing pressing 'enter' in DOM.js does lots of things: sets heading, article, gif. The button click listener doesn't do anything! Which is why none of us could get the site to work at first :)

https://github.com/fac-14/HMEN/blob/3bb71dfc878205f52110bfe09f5e5c13754aa349/public/DOM.js#L25

**Comment by sima-qian** [comment]
This was due to running out of time, I'm afraid
